# fly.toml app configuration file generated for astraee-discord-bot on 2025-09-27T06:29:23Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'astraee-discord-bot'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 768
