version: 0.0.0
services:
  - type: web
    name: astraee-discord-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
